databases:
  - name: ai_todo_planner
    databaseName: ai_todo_planner_sql
    user: ai_todo_planner_sql_user
    region: singapore

services:
  - type: web
    name: ai_todo_planner
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ai_todo_planner
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
